### ISSUE TITLE
how to add players

### ISSUE THREAD

**Issue by moh1122** [cuijing1991/PokerGameApp#1]
hello nice app but how to add players is it via bluetooth, peer 2 peer ?

**Comment by cuijing1991** [comment]
I used multipeer connectivity framework(MPC) . It is supposed to work both by local wifi or bluetooth. But I can only make it work via local wifi, I haven't figured out why bluetooth doesn't work.

**Comment by moh1122** [comment]
ooh ok i used local wifi but after i add friend how can i join the game and play?

**Comment by cuijing1991** [comment]
Hi, sorry for the confusion. You have to tap on three devices in the list and click "add select friends", it's a button. And the accept the request from the other three devices. After that, on host device, the right arrow on top will be enabled. Click the arrow to start game.
